name: Build and Push Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          docker build --push --platform linux/arm/v7 -t 08021986/meal-planner-fe-v2:${GITHUB_SHA} -t 08021986/meal-planner-fe-v2:latest .
